<style>

    /* for theme display pages */

    tr#row_christmas_general_themepos select#christmas_general_themepos {
        overflow-x: hidden;
        overflow-y: scroll;
        height: 100px !important;
    }


    .adminhtml-system_config-edit tr#row_christmas_christmasDecoration_imageSelect img,
    .adminhtml-system_config-edit tr#row_christmas_christmasImage_imageSelect img,
    .adminhtml-system_config-edit tr#row_christmas_headerSettings_imageSelect img {
        width: 30%;
    }

    .adminhtml-system_config-edit tr#row_christmas_gifSettings_imageSelect {
        width: 70%;
    }
</style>